---
- name: Import RPM-GPG-KEY-remi2018.
  rpm_key:
    state: "present"
    key: https://rpms.remirepo.net/RPM-GPG-KEY-remi2019

- name: Install Remi Repository(Fedora).
  dnf:
    state: "present"
    name: "https://rpms.remirepo.net/fedora/remi-release-{{ ansible_distribution_major_version }}.rpm"
