---
- name: Install EPEL Repository.
  package:
    name: "epel-release"
    state: "present"
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: Install Remi Repository(RHL).
  package:
    name: "https://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm"
    state: "present"
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: Install Remi Repository(Fedora).
  package:
    name: "https://rpms.remirepo.net/fedora/remi-release-{{ ansible_distribution_major_version }}.rpm"
    state: "present"
  when: ansible_distribution == "Fedora"
