---
- name: Install EPEL Repository.
  package:
    name: "epel-release"
    state: "present"

- name: Install Remi Repository(RHL).
  package:
    name: "https://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm"
    state: "present"
  when: ansible_distribution == "CentOS"

- rpm_key:
    state: present
    key: https://rpms.remirepo.net/RPM-GPG-KEY-remi2018
  when: ansible_distribution == "RedHat"

- name: Install Remi Repository(RHL).
  dnf:
    name: "https://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm"
    state: "present"
  when: ansible_distribution == "RedHat"

- rpm_key:
    status: present
    key: https://rpms.remirepo.net/RPM-GPG-KEY-remi2019
  when: ansible_distribution == "Fedora"

- name: Install Remi Repository(Fedora).
  dnf:
    name: "https://rpms.remirepo.net/fedora/remi-release-{{ ansible_distribution_major_version }}.rpm"
    state: "present"
  when: ansible_distribution == "Fedora"
