---
- name: Install EPEL Repository.
  package:
    state: "present"
    name: "epel-release"
  when: ansible_distribution == "CentOS"

- name: Install RPM-GPG-KEY-remi.
  rpm_key:
    state: "present"
    key: https://rpms.remirepo.net/RPM-GPG-KEY-remi
  when: ansible_distribution == "CentOS"

- name: Install Remi Repository(RHL).
  package:
    state: "present"
    name: "https://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm"
  when: ansible_distribution == "CentOS"

- name: Install RPM-GPG-KEY-remi2018.
  rpm_key:
    state: "present"
    key: "https://rpms.remirepo.net/RPM-GPG-KEY-remi2018"
  when: ansible_distribution == "RedHat"

- name: Install RPM-GPG-KEY-EPEL-8.
  rpm_key:
    state: present
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
  when: ansible_distribution == "RedHat"

- name: Install EPL Repository.
  dnf:
    state: "present"
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm"
  when: ansible_distribution == "RedHat"

- name: Install Remi Repository(RHL).
  dnf:
    state: "present"
    name: "https://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm"
  when: ansible_distribution == "RedHat"

- name: Install RPM-GPG-KEY-remi2019.
  rpm_key:
    state: "present"
    key: "https://rpms.remirepo.net/RPM-GPG-KEY-remi2019"
  when: ansible_distribution == "Fedora"

- name: Install Remi Repository(Fedora).
  dnf:
    state: "present"
    name: "https://rpms.remirepo.net/fedora/remi-release-{{ ansible_distribution_major_version }}.rpm"
  when: ansible_distribution == "Fedora"
